name: Deploy Power Apps Solution

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Power Platform CLI
        uses: microsoft/powerplatform-actions/setup-cli@v1
        with:
          pac-version: 'latest'

      - name: Authenticate to Power Platform (Dev Environment)
        uses: microsoft/powerplatform-actions/authenticate@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          authority-url: 'https://login.microsoftonline.com/${{ secrets.TENANT_ID }}'
          environment-url: 'https://make.powerautomate.com/environments/3b81f68d-2b2a-e383-af3a-ddca5c02afd4'

      - name: Export Solution from Development
        run: pac solution export --name "solution1testing" --path "./solutions/solution.zip"

      - name: Authenticate to Power Platform (Prod Environment)
        uses: microsoft/powerplatform-actions/authenticate@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          authority-url: 'https://login.microsoftonline.com/${{ secrets.TENANT_ID }}'
          environment-url: 'https://make.powerapps.com/environments/f3d358ea-b7df-ea8d-92b8-3a6ecf6b3dd8'

      - name: Import Solution to Production
        run: pac solution import --path "./solutions/solution.zip" --overwrite-unmanaged
